/* 高清像素角色头像层 v2 */
(function(g){"use strict";
var IDS=["hero_ref","zhou","su","shishu","aqing","jian_tong","yubo","shuizei","qianliu","stall","luyun","shen_wai","tieba","helie_npc","he_forge","yaotong","ao_sailor","que_shadow","monk_jing","hermit","xie_ren","reef_ghost","cave_guard"];
var META={
 hero_ref:{gender:"男",role:"player",tone:"gold",title:"江湖行者"},zhou:{gender:"男",role:"merchant",tone:"warm",title:"客栈掌柜"},su:{gender:"女",role:"doctor",tone:"jade",title:"医馆大夫"},shishu:{gender:"男",role:"storyteller",tone:"amber",title:"说书人"},aqing:{gender:"女",role:"herbalist",tone:"green",title:"采药人"},jian_tong:{gender:"男",role:"swordsman",tone:"steel",title:"江湖剑客"},yubo:{gender:"男",role:"ferryman",tone:"blue",title:"摆渡人"},shuizei:{gender:"男",role:"outlaw",tone:"red",title:"水寨匪徒"},qianliu:{gender:"男",role:"blackmarket",tone:"violet",title:"黑市商贩"},stall:{gender:"女",role:"vendor",tone:"warm",title:"街市摊主"},luyun:{gender:"男",role:"swordsman",tone:"mist",title:"江湖客"},shen_wai:{gender:"男",role:"official",tone:"steel",title:"官府中人"},tieba:{gender:"男",role:"outlaw",tone:"red",title:"亡命徒"},helie_npc:{gender:"男",role:"smith",tone:"ember",title:"铁匠"},he_forge:{gender:"男",role:"smith",tone:"ember",title:"铁匠"},yaotong:{gender:"女",role:"herbalist",tone:"green",title:"药童"},ao_sailor:{gender:"男",role:"sailor",tone:"blue",title:"江上船夫"},que_shadow:{gender:"其他",role:"shadow",tone:"dark",title:"神秘人"},monk_jing:{gender:"男",role:"monk",tone:"jade",title:"僧人"},hermit:{gender:"男",role:"elder",tone:"mist",title:"隐士"},xie_ren:{gender:"男",role:"evil",tone:"red",title:"凶徒"},reef_ghost:{gender:"其他",role:"shadow",tone:"dark",title:"礁影"},cave_guard:{gender:"其他",role:"shadow",tone:"dark",title:"洞窟守卫"}
};
g.AVATAR_IDS=IDS;g.AVATAR_META=META;g.AVATAR_HAS=function(id){return IDS.indexOf(id)>=0};g.AVATAR_SRC=function(id){return"./assets/avatars/"+id+".svg"};
function style(){if(!document||document.getElementById("avatar-ui-style"))return;var s=document.createElement("style");s.id="avatar-ui-style";s.textContent=".px-avatar{display:inline-grid;place-items:center;position:relative;overflow:hidden;vertical-align:middle;flex:0 0 auto;background:#17120f;border:1px solid #4b3a2d;box-shadow:0 3px 10px rgba(0,0,0,.28);transition:transform .16s ease,box-shadow .16s ease,border-color .16s ease}.px-avatar svg{display:block;width:100%;height:100%;shape-rendering:crispEdges;image-rendering:pixelated}.px-avatar img{display:block;width:100%;height:100%;object-fit:cover;image-rendering:auto}.px-avatar.sm{width:38px;height:38px}.px-avatar.md{width:58px;height:58px}.px-avatar.lg{width:88px;height:88px}.px-avatar.xl{width:120px;height:120px}.px-avatar.npc:hover{transform:translateY(-1px);box-shadow:0 6px 16px rgba(0,0,0,.34);border-color:#d9ad62}.px-avatar.tone-gold{border-color:#d9ad62}.px-avatar.tone-jade{border-color:#6f9f7c}.px-avatar.tone-red{border-color:#a95c55}.px-avatar.tone-blue{border-color:#607f9d}.px-avatar.tone-ember{border-color:#b9784e}.px-avatar.tone-violet{border-color:#8d70a4}.px-avatar.tone-steel{border-color:#8391a0}.px-avatar.tone-mist{border-color:#8d9a91}.px-avatar:after{content:'';position:absolute;inset:0;pointer-events:none;background:linear-gradient(135deg,rgba(255,255,255,.08),transparent 38%,rgba(0,0,0,.12));mix-blend-mode:screen}.avatar-card{display:flex;align-items:center;gap:10px;padding:8px 10px;border:1px solid #4b3a2d;border-radius:10px;background:linear-gradient(135deg,#211914,#17120f);min-width:0}.avatar-card .avatar-main{min-width:0;flex:1}.avatar-card .avatar-name{font-weight:700;color:#f5e8cf;font-size:14px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.avatar-card .avatar-title{font-size:10px;color:#b9a58a;margin-top:2px}.avatar-detail{font-size:9px;color:#8f806d;margin-top:3px}.avatar-mood{display:inline-block;margin-left:5px;padding:1px 5px;border-radius:99px;font-size:9px;border:1px solid #4b3a2d;color:#b9a58a}.avatar-mood.friendly{color:#7aae6a;border-color:#5f8055}.avatar-mood.trusted{color:#d9ad62;border-color:#9a7948}@media(max-width:600px){.px-avatar.md{width:54px;height:54px}.px-avatar.lg{width:78px;height:78px}}@media(min-resolution:2dppx){.px-avatar{box-shadow:0 3px 12px rgba(0,0,0,.3)}}";document.head.appendChild(s)}
function mood(f){f=f|0;if(f>=80)return{name:"知交",cls:"trusted"};if(f>=40)return{name:"相熟",cls:"friendly"};if(f<10)return{name:"陌路",cls:""};return{name:"相识",cls:"friendly"}}
g.avatarMood=function(p,id){if(!p||!id||typeof getFavor!=="function")return"";var m=mood(getFavor(p,id));return'<span class="avatar-mood '+m.cls+'">'+m.name+'</span>'};
function safe(id){return String(id||"unknown").replace(/[^a-zA-Z0-9_-]/g,"_")}
g.avatarFromLib=function(id,size,extra){if(!id)return null;size=size||"md";var m=META[id]||{},c="px-avatar "+size+" npc tone-"+(m.tone||"gold")+(extra?" "+extra:"");if(g.AVATAR_PACK&&g.AVATAR_PACK[id])return'<span class="'+c+'" data-avatar-id="'+safe(id)+'">'+g.AVATAR_PACK[id]+"</span>";return null};
function gen(seed,gender,role,preset){if(typeof pixelAvatarSvg!=="function")return"";try{return pixelAvatarSvg({seed:seed,gender:gender||"其他",role:role||"npc",presetId:preset||seed,resolution:120,detail:2})}catch(e){return""}}
g.preloadAvatars=function(){if(g.__avatarPreloaded)return;g.__avatarPreloaded=1;IDS.forEach(function(id){var m=META[id]||{};gen(id,m.gender,m.role,id)})};
g.registerAvatar=function(id,meta){if(!id||IDS.indexOf(id)>=0)return;IDS.push(id);if(meta)META[id]=meta};
function base(seed,gender,role,size,id){size=size||"md";id=id||seed;var p=avatarFromLib(id,size);if(p)return p;var svg=gen(seed,gender,role,id),m=META[id]||{};if(!svg)return'<span class="px-avatar '+size+' npc tone-'+(m.tone||"gold")+'">侠</span>';return'<span class="px-avatar '+size+' npc tone-'+(m.tone||"gold")+'" data-avatar-id="'+safe(id)+'">'+svg+'</span>'}
function bridge(){style();if(typeof avatarHtml!=="function"||avatarHtml._enhancedV2)return;var old=avatarHtml;function a(seed,gender,role,size,id){var x=id||seed,p=avatarFromLib(x,size||"md");if(p)return p;var m=META[x]||{},r=old(seed,gender,role,size||"md",id);return'<span class="px-avatar '+(size||"md")+' npc tone-'+(m.tone||"gold")+'" data-avatar-id="'+safe(x)+'">'+r+'</span>'}a._enhancedV2=true;g.avatarHtml=a;g.playerAvatar=function(p,size){return a((p&&p.name)||"player",(p&&p.gender)||"男","player",size||"md","hero_ref")};g.npcAvatar=function(n,size){n=n||{};var id=n.id||n.name||"unknown",m=META[id]||{},gen=m.gender||"其他";if(typeof getNpcProfile==="function"){try{var q=getNpcProfile(n);if(q&&q.gender){var z=String(q.gender);if(z.indexOf("女")>=0)gen="女";else if(z.indexOf("男")>=0)gen="男"}}catch(e){}}return a(id,gen,m.role||"npc",size||"md",id)} }
g.avatarCardHtml=function(n,p,size){if(!n)return"";var id=n.id||n.name||"unknown",m=META[id]||{},av=g.npcAvatar?g.npcAvatar(n,size||"md"):base(id,m.gender,m.role,size,id),mo=g.avatarMood?g.avatarMood(p,id):"",title=n.title||m.title||"江湖人物";return'<div class="avatar-card">'+av+'<div class="avatar-main"><div class="avatar-name">'+(n.name||"未知人物")+mo+'</div><div class="avatar-title">'+title+'</div><div class="avatar-detail">'+(m.role||"")+'</div></div></div>'};
function boot(){style();bridge();g.preloadAvatars()}if(typeof document!=="undefined"){if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",function(){setTimeout(boot,0)});else setTimeout(boot,0)}setTimeout(boot,50);setTimeout(boot,200)
})(typeof window!=="undefined"?window:this);