const npcs=[
{id:"zhou",name:"老周",title:"客栈掌柜",loc:"qinghe",desc:"清河镇客栈老板，消息灵通，店里常有过路武人落脚。",talks:["江湖险恶，少侠且先吃饭。肚里空着，剑也握不稳。","缉武司最近在查黑盐古道的人，过路时少惹事。","烟岚剑斋收徒严，听说要在云雾里走完山道才算过关。","你若缺银子，可去旧瓦市碰碰运气，也可帮我搬货。","北来的刀客说血石峡谷又不太平了。"],acts:[{id:"rest",name:"住店恢复",type:"rest",cost:8,hp:30,mp:20},{id:"rumor",name:"打听消息",type:"talk"},{id:"work",name:"帮工赚银",type:"silver",value:10}]},
{id:"su",name:"苏半仙",title:"医馆大夫",loc:"qinghe",desc:"医术尚可，脾气一般，常抱怨江湖人不会惜命。",talks:["先把命保住，再谈武功。死人学不会剑。","回春谷的药最好，但贵。我这里的金创药也够用。","内息紊乱？少打那些有的没的，好好吐纳。","你这根骨……勉勉强强，别硬拼。"],acts:[{id:"heal",name:"诊治回血",type:"heal",cost:15,value:40},{id:"buy_pill",name:"买金创药",type:"item",cost:20,effect:"heal",value:35}]},
{id:"shishu",name:"王说书",title:"茶棚说书人",loc:"qinghe",desc:"摆着醒木，专讲缉武司与江湖秘闻。",talks:["且听我道：大雍末年，武林风云再起……","白雀楼的人来无影去无踪，打听他们的，多半失踪。","玄鲸帮主敖沧，一根鲸骨杖，毁约者沉海。","你可愿出点茶钱，听段新鲜的？"],acts:[{id:"story",name:"听书",type:"talk"},{id:"tip_coin",name:"赏茶钱听秘闻",type:"exp",cost:5,value:12}]},
{id:"aqing",name:"阿青",title:"采药人",loc:"bamboo",desc:"常在竹径采药的少女，认得许多药草。",talks:["这雨里的竹叶能止血，别小看了。","山门那边弟子有时会下来练剑，剑光像烟。","毒蛇喜欢躲在湿石头下，你小心点。","回春谷谷主苏青萝，人美心善，掌却很重。"],acts:[{id:"herb",name:"买草药",type:"item",cost:12,effect:"heal",value:20},{id:"guide",name:"请教路径",type:"talk"}]},
{id:"jian_tong",name:"竹间",title:"练剑少年",loc:"bamboo",desc:"独自在竹林练剑，剑招生疏却认真。",talks:["我想去烟岚剑斋，可是身法还不够。","竹叶落下来时，我试着一剑劈开……总劈不中。","你若会剑，能指点一二吗？"],acts:[{id:"spar_kid",name:"指点他两招",type:"exp",cost:0,value:8},{id:"encourage",name:"鼓励几句",type:"talk"}]},
{id:"yubo",name:"老余",title:"渡船船夫",loc:"ferry",desc:"走南闯北几十年，手上全是纤绳勒出的茧。",talks:["南海商盟的船最阔气，护船银子也多。","水贼专欺负弱的，战力低就别逞能。","潮生那小子在玄鲸港，问起我准让你上船。","江风养人，你在这吐纳一阵也好。"],acts:[{id:"ferry_tip",name:"打听水路",type:"talk"},{id:"train_swim",name:"学水性",type:"train_stat",stat:"qi",cost:25,value:1,once:true}]},
{id:"shuizei",name:"独眼",title:"落魄水贼",loc:"ferry",desc:"少了一只眼，声称已金盆洗手。",talks:["老子以前……算了，不提了。","黑盐古道上的刀客，比水贼还狠。","你要是缺暗器，去旧瓦市找钱六。"],acts:[{id:"threat",name:"试探他",type:"duel",diff:38,dmg:16,reward:14},{id:"buy_info",name:"买他嘴上的消息",type:"talk",cost:8}]},
{id:"qianliu",name:"钱六",title:"黑市贩子",loc:"market",desc:"什么都卖，真假难辨，笑起来像狐狸。",talks:["残谱？有。贵。假的也有，更贵——因为难辨。","别问货从哪来。问了，你就得买。","白雀楼的人路过时，连影子都不留。","赌一把？输了别找我，赢了请我喝酒。"],acts:[{id:"sell_needle",name:"飞星针谱",type:"skill",skill:"throwing_needle",cost:25},{id:"sell_point",name:"点穴手残页",type:"skill",skill:"point_finger",cost:30},{id:"gamble",name:"赌一把",type:"gamble",cost:20}]},
{id:"stall",name:"张婆",title:"炊饼摊主",loc:"market",desc:"卖炊饼为生，耳尖，知道不少市井闲话。",talks:["吃口热的再走。空肚子打架，先输一半。","夜里有人从白雀楼方向过来，脚步轻得像猫。","缉武司的人装成客商，我一眼就瞧出来了。"],acts:[{id:"eat",name:"买炊饼",type:"heal",cost:5,value:15},{id:"gossip",name:"拉家常",type:"talk"}]},
{id:"luyun",name:"陆云",title:"外门弟子",loc:"mist_gate",desc:"烟岚剑斋外门，话不多，剑穗上沾着露水。",talks:["斋主最看重悟性。蛮力在这里用处不大。","云雾中练剑，心不能乱，乱则剑偏。","你若想拜入，先把身法练起来。","内门师兄偶尔下山，那才是真剑。"],acts:[{id:"spar",name:"比剑切磋",type:"duel",diff:35,dmg:18,reward:15},{id:"tip",name:"请教剑意",type:"exp",cost:10,value:20}]},
{id:"shen_wai",name:"沈疏",title:"外门执事",loc:"mist_gate",desc:"负责外门杂务与记名弟子登记。",talks:["记名容易，入门难。贡献与心性都要过关。","山道上的贼人清过一轮，又冒出来了。","斋主沈听云，三年只收过两个亲传。"],acts:[{id:"chore",name:"帮外门杂务",type:"silver",value:8},{id:"ask_rule",name:"询问门规",type:"talk"}]},
{id:"tieba",name:"铁疤",title:"流浪刀客",loc:"salt_road",desc:"脸上有刀疤，眼神狠，腰间刀柄磨得发亮。",talks:["这道上死人比活人多。想活，就别心软。","血石峡谷里的邪修，吃人不吐骨头。","你的刀……还是剑？握紧点。","赤炉刀社的贺烈，一刀断石，我服。"],acts:[{id:"duel_knife",name:"刀下见真章",type:"duel",diff:55,dmg:28,reward:30},{id:"buy_oil",name:"买刀油",type:"exp",cost:20,value:25}]},
{id:"helie_npc",name:"贺炉",title:"锻刀学徒",loc:"hearth",desc:"赤炉刀社的年轻学徒，手臂有烫伤。",talks:["社主的刀，一刀断石。我还差得远。","搬矿也能长力气，别嫌弃粗活。","假刀坑商害了不少走镖的，社主正在查。","炉火正旺，你要试刀吗？"],acts:[{id:"help_ore",name:"帮忙搬矿",type:"silver",value:12},{id:"spar_blade",name:"试刀",type:"duel",diff:42,dmg:20,reward:18}]},
{id:"he_forge",name:"石匠老金",title:"铸兵匠",loc:"hearth",desc:"负责打磨刀锋，话少，锤子很响。",talks:["刀要养，人也要养。别只会砍。","炉心有异动时，整座山都会震。","你这兵器……算了，不评价。"],acts:[{id:"polish",name:"求他磨刀",type:"exp",cost:15,value:18},{id:"listen_forge",name:"听他讲铸兵",type:"talk"}]},
{id:"yaotong",name:"药童",title:"回春谷弟子",loc:"herb_valley",desc:"背着药篓，笑眯眯，能分清上百种草。",talks:["谷主说，救人比杀人难，也比杀人重要。","误食毒草会很惨，我见过一次，不想再看。","瘟疫的征兆是夜里咳血，你若见到，快来报。","辨药先看叶脉，再闻气味。"],acts:[{id:"free_heal",name:"请施药",type:"heal",cost:8,value:45},{id:"learn_herb",name:"学辨药",type:"train_stat",stat:"wit",cost:30,value:1,once:true}]},
{id:"ao_sailor",name:"潮生",title:"玄鲸帮众",loc:"whale_port",desc:"皮肤晒得发黑的水手，腰间挂着贝壳。",talks:["帮规重契约。毁约者，海葬。","深海里有东西在动，老帮众都不愿提。","护船银子不错，但风浪大时很危险。","帮主敖沧的鲸骨杖，沾过不少毁约之人的血。"],acts:[{id:"guard_ship",name:"护船一程",type:"duel",diff:48,dmg:22,reward:25},{id:"pearl",name:"买潮珠",type:"item",cost:35,effect:"mp",value:40}]},
{id:"que_shadow",name:"影七",title:"白雀影卫",loc:"sparrow_den",desc:"看不清面容的黑衣人，声音像从远处传来。",talks:["……","楼里不欢迎废话。","传信要快、要静、要活着回来。","你的脚步太重了。"],acts:[{id:"msg",name:"传信赚钱",type:"silver",value:16},{id:"shadow_train",name:"学影步",type:"exp",cost:15,value:28}]},
{id:"monk_jing",name:"静尘",title:"无相寺僧",loc:"void_temple",desc:"年轻僧人，目不斜视，念珠磨得发亮。",talks:["无相无我。执着便是心魔。","心魔比外敌更难降，因为它住在你心里。","方丈空观虽盲，一指可断金。","抄经不是罚，是磨心。"],acts:[{id:"copy_sutra",name:"抄经感悟",type:"exp",cost:0,value:22},{id:"meditation",name:"打坐",type:"rest",cost:0,hp:10,mp:35}]},
{id:"hermit",name:"云叟",title:"隐士",loc:"cloud_peak",desc:"白发老者，坐在残碑旁，像已经坐了一百年。",talks:["天机不可尽说。说尽了，便不是天机。","你的缘法未到……或许到了，你自己还不知道。","云海下面，是人争名夺利；云海上面，只有风。","福缘这东西，求不来，但可以不拒绝。"],acts:[{id:"ask_dao",name:"请教天机",type:"talk"},{id:"gift_luck",name:"求福缘",type:"train_stat",stat:"luck",cost:50,value:1,once:true}]},
{id:"xie_ren",name:"血屠",title:"邪修",loc:"blood_ravine",desc:"衣衫染血，笑容诡异，刀上还滴着什么。",talks:["正道？呵。正道杀的人，不比我少。","刀下亡魂，我记得每一个——记得他们求饶的样子。","你若怕，现在就滚。","血海狂刀……有兴趣吗？"],acts:[{id:"blood_duel",name:"血战",type:"duel",diff:65,dmg:35,reward:40},{id:"evil_tip",name:"邪功残页",type:"exp",cost:30,value:40}]},
{id:"reef_ghost",name:"沉沙",title:"遗迹看守",loc:"secret_reef",desc:"像是石头里长出来的人影，声音像潮汐。",talks:["潮汐会打开门。不懂古法，勿近。","这里沉过一整个船队，银子和骨头埋在一起。","古法吐纳，与人间内功不同。","你听见鼓声了吗？那是潮，也是心跳。"],acts:[{id:"ancient",name:"观摩古法",type:"exp",cost:20,value:45},{id:"dive",name:"潜海寻物",type:"duel",diff:70,dmg:32,reward:50}]},
{id:"cave_guard",name:"窟影",title:"密道机关人",loc:"secret_cave",desc:"不知是人是傀，关节处有金属声。",talks:["……咔。","禁止通行。","机关已启。","影中……有人。"],acts:[{id:"disarm",name:"拆机关",type:"duel",diff:58,dmg:26,reward:35},{id:"sneak",name:"潜行练习",type:"exp",cost:10,value:30}]}
];
function getNpcsAt(loc){return npcs.filter(function(n){return n.loc===loc;});}
function findPerson(id){return npcs.find(function(n){return n.id===id;});}
