/* world_map_v2.js — 天下舆图
 * 唯一城市/路线数据源：data/world.json
 * 江湖点数据源：data/maps.json
 * 城市游历数据源：data/city_content.json
 */
(function(g){
  "use strict";
  var KIND={road:"官道",canal:"运河",river:"江路",sea:"海路",mountain:"蜀道"};
  function source(){return g.world&&g.world.worldMap&&g.world.worldMap.cities&&Array.isArray(g.world.worldMap.edges)?g.world.worldMap:null;}
  function cities(){var w=source(),out={};if(!w)return out;Object.keys(w.cities).forEach(function(id){var c=w.cities[id]||{};out[id]={id:id,name:c.name||id,alias:c.alias||"",region:c.region||"",tag:c.tag||"",desc:c.desc||"",children:Array.isArray(c.children)?c.children.slice():[]};});return out;}
  function edges(){var w=source();return w?w.edges.map(function(e){return[e[0],e[1],Number(e[2])||1,e[3]||"road"]}):[];}
  function city(id){return cities()[id]||null;}
  function neighbors(id){var C=cities(),E=edges(),a=[];E.forEach(function(e){if(e[0]===id&&C[e[1]])a.push({id:e[1],city:C[e[1]],cost:e[2],kind:e[3]});if(e[1]===id&&C[e[0]])a.push({id:e[0],city:C[e[0]],cost:e[2],kind:e[3]});});return a;}
  function owner(loc){var C=cities(),m=typeof getMapById==="function"?getMapById(loc):null;if(m&&m.parent&&C[m.parent])return m.parent;for(var id in C)if(C[id].children.indexOf(loc)>=0)return id;return null;}
  function path(a,b){var C=cities();if(!C[a]||!C[b])return null;if(a===b)return[a];var q=[a],prev={};prev[a]=null;while(q.length){var cur=q.shift(),ns=neighbors(cur);for(var i=0;i<ns.length;i++){var n=ns[i].id;if(prev[n]!==undefined)continue;prev[n]=cur;if(n===b){var r=[n],x=cur;while(x){r.push(x);x=prev[x];}return r.reverse();}q.push(n);}}return null;}
  function edge(a,b){var E=edges();for(var i=0;i<E.length;i++)if((E[i][0]===a&&E[i][1]===b)||(E[i][0]===b&&E[i][1]===a))return{cost:E[i][2],kind:E[i][3]};return null;}
  function travel(p,to){var C=cities();if(!p||!C[to])return{ok:false,msg:"未知州府"};var from=p.worldLocation||owner(p.location);if(!from||!C[from])return{ok:false,msg:"当前江湖点尚未登记所属州府"};if(from===to)return{ok:false,msg:"已经在"+C[to].name};var route=path(from,to);if(!route)return{ok:false,msg:"没有可用的城际路线"};var days=0;for(var i=0;i<route.length-1;i++){var e=edge(route[i],route[i+1]);if(!e)return{ok:false,msg:"路线数据不完整"};days+=e.cost;}var unit=typeof TIME_COST!=="undefined"&&TIME_COST.move!=null?TIME_COST.move:1;if(typeof advanceTime==="function")advanceTime(p,days*unit);p.worldLocation=to;if(!Array.isArray(p.worldVisited))p.worldVisited=[];if(p.worldVisited.indexOf(to)<0)p.worldVisited.push(to);if(!Array.isArray(p.logs))p.logs=[];p.logs.unshift("经"+route.map(function(x){return C[x].name;}).join(" → ")+"，抵达"+C[to].name+"，耗时"+days+"日。");p.logs=p.logs.slice(0,50);if(g.Game&&Game.emit)Game.emit("world:travel",{from:from,to:to,route:route,days:days});return{ok:true,from:from,to:to,route:route,days:days};}
  function enter(p,cityId,spotId){var C=cities();if(!p||!C[cityId])return{ok:false,msg:"未知州府"};if(spotId&&C[cityId].children.indexOf(spotId)>=0){p.location=spotId;p.worldLocation=cityId;return{ok:true,location:spotId};}p.worldLocation=cityId;return{ok:true,children:C[cityId].children.slice()};}
  function esc(s){return String(s==null?"":s).replace(/[&<>\"']/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]||c;});}
  function close(){var e=document.getElementById("worldMapV2");if(e)e.remove();}
  function open(){var p=g.state&&g.state.player||g.player;if(!p)return;var C=cities(),root=document.getElementById("modalRoot");if(!root)return;var cur=p.worldLocation||owner(p.location)||Object.keys(C)[0],current=C[cur];if(!current)return;var html='<div class="modal-mask" id="worldMapV2"><div class="modal-panel"><div class="modal-head"><h3 class="section-title">天下舆图</h3><button class="modal-close" onclick="worldV2Close()">关闭</button></div><div class="world-v2-current"><b>'+esc(current.name)+'</b><span>'+esc(current.alias)+' · '+esc(current.region)+' · '+esc(current.tag)+'</span><p>'+esc(current.desc)+'</p><p>当前江湖点：'+esc((typeof getMapById==="function"&&getMapById(p.location)?getMapById(p.location).name:p.location||"未知"))+'</p></div><div class="world-v2-grid">';Object.keys(C).forEach(function(id){var near=neighbors(cur).some(function(n){return n.id===id;}),active=id===cur,visited=Array.isArray(p.worldVisited)&&p.worldVisited.indexOf(id)>=0;html+='<button class="world-v2-city '+(active?"active ":"")+(near?"near ":"")+(visited?"visited":"")+'" onclick="worldV2Travel(\''+id+'\')"><b>'+esc(C[id].name)+'</b><small>'+esc(C[id].alias)+' · '+esc(C[id].region)+'</small><i>'+esc(C[id].tag)+'</i></button>';});html+='</div><div class="section-title">当前可达路线</div><div class="world-v2-routes">';neighbors(cur).forEach(function(n){html+='<div><span>'+esc(n.city.name)+' · '+esc(KIND[n.kind]||n.kind)+'</span><b>'+n.cost+'日</b></div>';});if(!neighbors(cur).length)html+='<div class="small">当前州府暂无可用城际路线。</div>';html+='</div><div class="section-title">城市游历</div><div class="small">进入州府后，可从城市游历获得银两、历练、属性、气血、内力或见闻。</div><button class="btn" style="width:100%;margin-top:7px" onclick="cityExploreOpen(\''+cur+'\')">探索'+esc(current.name)+'</button><div class="small" style="margin-top:7px">城市与路线均来自 data/world.json；城市 Explore 来自 data/city_content.json。</div></div></div>';root.innerHTML=html;}
  g.WORLD_MAP_LAYERED={city:city,cities:cities,edges:edges,neighbors:neighbors,owner:owner,path:path,travel:travel,enter:enter,open:open};g.worldV2Close=close;
  g.worldV2Travel=function(id){var r=travel(g.state&&g.state.player||g.player,id);if(!r.ok){if(typeof showToast==="function")showToast(r.msg);else alert(r.msg);return;}open();if(typeof renderGame==="function")renderGame();};
  function install(){if(typeof document==="undefined")return;var bars=document.querySelectorAll(".toolbar");for(var i=0;i<bars.length;i++){var bar=bars[i];if(bar.querySelector("[data-world-v2]"))continue;var b=document.createElement("button");b.className="btn sm";b.textContent="天下舆图";b.dataset.worldV2="1";b.onclick=open;bar.appendChild(b);}}
  function style(){if(document.getElementById("world-v2-style"))return;var s=document.createElement("style");s.id="world-v2-style";s.textContent='.world-v2-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin:8px 0}.world-v2-city{min-height:64px;text-align:left;padding:7px;background:#1a1512;color:#e8d7bd;border:1px solid #4b3a2d;border-radius:7px}.world-v2-city b{display:block;color:#f5e8cf}.world-v2-city small{display:block;color:#8f806d;font-size:9px;margin-top:2px}.world-v2-city i{display:block;color:#d9ad62;font-style:normal;font-size:9px;margin-top:3px}.world-v2-city.active{border-color:#d9ad62;background:#34271e}.world-v2-city.near{box-shadow:inset 0 0 0 1px rgba(217,173,98,.18)}.world-v2-city.visited{border-bottom-color:#7aae6a}.world-v2-current{padding:8px;border:1px solid #4b3a2d;background:#1a1512;border-radius:8px;margin-bottom:8px}.world-v2-current b{color:#d9ad62;font-size:17px}.world-v2-current span{font-size:10px;color:#b9a58a;margin-left:6px}.world-v2-current p{font-size:11px;color:#d8c6aa;margin:5px 0}.world-v2-routes>div{display:flex;justify-content:space-between;padding:5px 2px;border-bottom:1px dashed rgba(75,58,45,.35);font-size:11px}.world-v2-routes b{color:#d9ad62}@media(max-width:600px){.world-v2-grid{grid-template-columns:repeat(2,1fr)}}';document.head.appendChild(s);}
  function boot(){style();install();}
  if(typeof document!=="undefined"){if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",function(){setTimeout(boot,0);});else setTimeout(boot,0);}
})(typeof window!=="undefined"?window:this);
